### PR TITLE
Remove v2 namespace for classifier

### PR DESCRIPTION
**Pull request by antonyoneill**
## Context

We introduced a v2 classifier that ran in parallel with the original until we were satisfied with the parity.

V2 was promoted a few weeks ago and removed in #476 however to finish the promotion we can now remove the delegation to v2.

## Changes proposed in this pull request

- Remove references to v2 namespace.
- Directory restructuring.

## Link to Jira card

https://hackney.atlassian.net/browse/MAAP-476

## Things to check

- [x] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [x] Environment variables have been updated

### CODE REVIEW

**Review by elena-vi — APPROVED** [review]
I'm a little confused about why `helpers_base` and `helpers_proxy` can't be the same file. 
But other than that everything looks good

**Review by C-gyorfi — APPROVED** [review]
LGTM 👍

**Comment by antonyoneill** [comment]
Next PR El :)

**Comment by C-gyorfi** [comment]
> I'm a little confused about why `helpers_base` and `helpers_proxy` can't be the same file.
> But other than that everything looks good

`helpers_proxy` is a temporary fix that allows us to switch between the old helpers(used UH data) and new helpers(used MA agreements/court cases data)

`helpers_base` is just a parent class to remove duplication from `MAAgreementHelpers` and `MACourtCaseHelpers`, unfortunately, there was some overlap we couldn't remove

**Pull request merged**
